import React, { useEffect } from "react";
import {
  HomeContainer,
  HomeContent,
  HomeCard,
  CardTitle,
  CardImage,
  CardDescription,
  FirstLine,
  SecondLine,
} from "./HomeElements";

const Home = () => {
  return (
    <HomeContainer>
      <HomeContent>
        <HomeCard>
          <CardTitle>Title</CardTitle>
          <CardImage></CardImage>
          <CardDescription>
            <FirstLine>
              <span>DESCRIPTION</span>
              <span>Date</span>
            </FirstLine>
            <SecondLine>
              <button>Edit</button>
              <button>Delete</button>
            </SecondLine>
          </CardDescription>
        </HomeCard>
        <HomeCard>
          <CardTitle>Title</CardTitle>
          <CardImage></CardImage>
          <CardDescription>
            <FirstLine>
              <span>DESCRIPTION</span>
              <span>Date</span>
            </FirstLine>
            <SecondLine>
              <button>Edit</button>
              <button>Delete</button>
            </SecondLine>
          </CardDescription>
        </HomeCard>
        <HomeCard>
          <CardTitle>Title</CardTitle>
          <CardImage></CardImage>
          <CardDescription>
            <FirstLine>
              <span>DESCRIPTION</span>
              <span>Date</span>
            </FirstLine>
            <SecondLine>
              <button>Edit</button>
              <button>Delete</button>
            </SecondLine>
          </CardDescription>
        </HomeCard>
        <HomeCard>
          <CardTitle>Title</CardTitle>
          <CardImage></CardImage>
          <CardDescription>
            <FirstLine>
              <span>DESCRIPTION</span>
              <span>Date</span>
            </FirstLine>
            <SecondLine>
              <button>Edit</button>
              <button>Delete</button>
            </SecondLine>
          </CardDescription>
        </HomeCard>
        <HomeCard>
          <CardTitle>Title</CardTitle>
          <CardImage></CardImage>
          <CardDescription>
            <FirstLine>
              <span>DESCRIPTION</span>
              <span>Date</span>
            </FirstLine>
            <SecondLine>
              <button>Edit</button>
              <button>Delete</button>
            </SecondLine>
          </CardDescription>
        </HomeCard>
        <HomeCard>
          <CardTitle>Title</CardTitle>
          <CardImage></CardImage>
          <CardDescription>
            <FirstLine>
              <span>DESCRIPTION</span>
              <span>Date</span>
            </FirstLine>
            <SecondLine>
              <button>Edit</button>
              <button>Delete</button>
            </SecondLine>
          </CardDescription>
        </HomeCard>
        <HomeCard>
          <CardTitle>Title</CardTitle>
          <CardImage></CardImage>
          <CardDescription>
            <FirstLine>
              <span>DESCRIPTION</span>
              <span>Date</span>
            </FirstLine>
            <SecondLine>
              <button>Edit</button>
              <button>Delete</button>
            </SecondLine>
          </CardDescription>
        </HomeCard>
        <HomeCard>
          <CardTitle>Title</CardTitle>
          <CardImage></CardImage>
          <CardDescription>
            <FirstLine>
              <span>DESCRIPTION</span>
              <span>Date</span>
            </FirstLine>
            <SecondLine>
              <button>Edit</button>
              <button>Delete</button>
            </SecondLine>
          </CardDescription>
        </HomeCard>
        <HomeCard>
          <CardTitle>Title</CardTitle>
          <CardImage></CardImage>
          <CardDescription>
            <FirstLine>
              <span>DESCRIPTION</span>
              <span>Date</span>
            </FirstLine>
            <SecondLine>
              <button>Edit</button>
              <button>Delete</button>
            </SecondLine>
          </CardDescription>
        </HomeCard>
        <HomeCard>
          <CardTitle>Title</CardTitle>
          <CardImage></CardImage>
          <CardDescription>
            <FirstLine>
              <span>DESCRIPTION</span>
              <span>Date</span>
            </FirstLine>
            <SecondLine>
              <button>Edit</button>
              <button>Delete</button>
            </SecondLine>
          </CardDescription>
        </HomeCard>
        <HomeCard>
          <CardTitle>Title</CardTitle>
          <CardImage></CardImage>
          <CardDescription>
            <FirstLine>
              <span>DESCRIPTION</span>
              <span>Date</span>
            </FirstLine>
            <SecondLine>
              <button>Edit</button>
              <button>Delete</button>
            </SecondLine>
          </CardDescription>
        </HomeCard>
        <HomeCard>
          <CardTitle>Title</CardTitle>
          <CardImage></CardImage>
          <CardDescription>
            <FirstLine>
              <span>DESCRIPTION</span>
              <span>Date</span>
            </FirstLine>
            <SecondLine>
              <button>Edit</button>
              <button>Delete</button>
            </SecondLine>
          </CardDescription>
        </HomeCard>
      </HomeContent>
    </HomeContainer>
  );
};

export default Home;
